(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`:
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

;; Exec path from shell initialize when emacs in server mode
(when (daemonp)
  (exec-path-from-shell-initialize))

(menu-bar-mode 0)
(tool-bar-mode 0)
(ido-mode 1)
(electric-pair-mode 1)

(setq backup-directory-alist '(("." . "~/.emacs_saves")) )

(use-package eglot :ensure t)
(use-package company :ensure t :config (global-company-mode))
(use-package nix-mode :ensure t)
(use-package rust-mode :ensure t)
(use-package zig-mode :ensure t)

(dolist (mode '(nix-mode-hook rust-mode-hook zig-mode-hook))
  (add-hook mode (lambda () (eglot-ensure) (company-mode))))

;; Smex package setup
  (global-set-key (kbd "M-x") 'smex)
  (global-set-key (kbd "M-X") 'smex-major-mode-commands)
  ;; This is your old M-x.
  (global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)

;;disable splash screen and startup message
(setq inhibit-startup-message t) 
;;(setq initial-scratch-message nil)

;; NEXT CODE IS AUTOMATICALLY GENERATED BY EMACS

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes '(gruber-darker))
 '(custom-safe-themes
   '("e27c9668d7eddf75373fa6b07475ae2d6892185f07ebed037eedf783318761d7" default))
 '(exec-path
   '("/run/wrappers/bin" "/home/mediacom/.nix-profile/bin" "/nix/profile/bin" "/home/mediacom/.local/state/nix/profile/bin" "/etc/profiles/per-user/mediacom/bin" "/nix/var/nix/profiles/default/bin" "/run/current-system/sw/bin" "/nix/store/0rk8dlblgpa2nkkiy9xlvm37h6is1hx5-emacs-nox-29.4/libexec/emacs/29.4/x86_64-pc-linux-gnu"))
 '(org-export-backends '(ascii html icalendar latex man md odt))
 '(package-selected-packages
   '(smex zig-mode rust-mode nix-mode gruber-darker-theme exec-path-from-shell consult-eglot company-math))
 '(server-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
